# -*- coding: utf-8 -*-
"""Financial_Analisys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kH584aoQGpJ2OglJ4F_ng4UlnXl3KIRr
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import random

Data_book = pd.read_excel ('/content/drive/MyDrive/Colab Notebooks/Financial Sample.xlsx')
Data_book

Data_book.info()

Data_book.describe()

Data_book.insert(0, 'Id Number', range(1000, 1700))
Data_book

data2=Data_book.sort_values(by= 'Discount Band',ascending=True)
data2

data3=Data_book.sort_values(by= 'Units Sold',ascending=True)
data3

"""# **Line Graph**"""

x = Data_book['Country'].head(20)
y = Data_book[' Sales'].head(20)

plt.xlabel('Countries')
plt.ylabel('Sales')
plt.title('Sales of carratera in $')
plt.plot(x,y, color='red')
plt.xticks(rotation = 'vertical')

plt.show()

"""# **Scatter Plot**"""

a = Data_book['Profit'].head(20)
plt.scatter(x, a)
plt.xticks(rotation = 'vertical')
plt.show()

"""# **Hystogram**"""

b = Data_book['Segment'].head(30)
a = Data_book['Profit'].head(50)
plt.hist(b)
plt.xlabel('Sector')
plt.ylabel('Profit')
plt.xticks(rotation = 45)

plt.show()

"""# **Bar Chart**"""

job_title_counts = Data_book['Segment'].value_counts()
job_title_counts_table = pd.DataFrame({'Segment': job_title_counts.index, 'Count': job_title_counts.values})
job_title_counts_table

c = job_title_counts_table['Segment'].tolist()
d = job_title_counts_table['Count'].tolist()
plt.bar(c, d, label='Job Titles', color='r')

plt.xlabel('Sectors')
plt.ylabel("Quantity")
plt.title("Branches")
plt.xticks(rotation = 45)
plt.legend()
plt.show()

"""## **Pie** **Chart**"""

x = Data_book['Country'].head(10)
a = Data_book['Gross Sales'].head(10)
plt.pie(a,labels=x, autopct='%2.1f%%')
plt.title('Gross Sale')
plt.show()

"""# **Swarm plot**"""

e=data3['Country'].head(20)
f=data3['Units Sold'].head(20)

import matplotlib.pyplot as plt
plt.figure(figsize=(13,8))
sb.swarmplot(x=e,y=f, data=data3, hue='Product', size=15)
plt.xticks(rotation = 60)
plt.show()

"""# **Pair Plot**"""

sb.set_style('darkgrid')                                                         # this the comand for changing background of the graph
sb.pairplot(Data_book, hue='Year', plot_kws={'s':50})
plt.show()

"""# **Box Plot**"""

import matplotlib.pyplot as plt
sb.boxplot(x='Product', y='Units Sold', data=data2.head(20))
plt.xticks(rotation = 45)
plt.show()

"""# **Grouped Bar Chart**"""

import matplotlib.pyplot as plt
import numpy as np
sectors = ['Government', 'Midmarket', 'Channel Partners', 'Enterprise', 'Small Business']
country = ['United States of America', 'Canada', 'Germany', 'Mexico', 'France']
products = ['Carretera', 'Montana', 'VTT', 'Paseo', 'Velo', 'Amarilla']

# Define the values for the x-axis and calculate the bar width
x = np.arange(len(sectors))
bar_width = 0.2

# Create the figure and axis
fig, ax = plt.subplots()

# Plot the bars for each category
rects1 = ax.bar(x - bar_width, [1, 0, 0, 1, 1], bar_width, label='sectors')
rects2 = ax.bar(x, [1, 1, 1, 1, 1], bar_width, label='country')
rects3 = ax.bar(x + bar_width, [1, 1, 1, 1, 0], bar_width, label='products')
ax.set_xlabel('Category')
ax.set_ylabel('Count')
ax.set_title('Grouped Bar Chart')
ax.set_xticks(x)
ax.set_xticklabels(sectors)
ax.legend()
plt.tight_layout()
plt.show()

"""# **T-test**"""

import scipy.stats as sc
import pandas as pd
from scipy.stats import ttest_ind

df = pd.DataFrame({'Product':['Carretera','Carretera','Carretera','Carretera','Carretera','Carretera','Carretera','Amarilla','Amarilla','Amarilla','Amarilla','Amarilla','Amarilla','Amarilla'],'Fat %': [1,1.25,1.50,1.75,2,2.25,2.50,1,1.50,2,2.50,3,3.50,4]})
df

group1 = df[df['Product']=='Carretera']
group2 = df[df['Product']=='Amarilla']
group1

ttest_ind(group1['Fat %'],group2['Fat %'])

"""The pvalue is greater than 0.05 proving that null hypothesis is not negligible  and there is significant difference in the Fat % of the Products.

# **Anova**
"""

import scipy.stats as sc
import pandas as pd
Carretera =[500,195,600,324,744]
Amarilla=[190,750,525,170,920]
Montana	=[140,125,290,211,415]
Vtt=[551,695,675,679,763]
Paseo=[677,757,229,709,558,800]
Velo=[855,539,712,795,905,2945]

sc.f_oneway(Carretera,Amarilla,Montana,Vtt,Paseo,Velo)

"""The pvalue is more than 0.05 proving that null hypothesis is not negligible  and there is quite significant difference in the Prices of the Products ."""

import matplotlib.pyplot as plt
h = Data_book['Discounts'].head(20)
plt.boxplot(h)
median = h.median()
plt.axhline(median, color='red', linestyle='--', label='Median')
plt.legend()
plt.show()
